<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.DependencyInjection" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="dbup-postgresql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModularOutbox.Core\ModularOutbox.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ModularOutbox.PostgreSQL.Tests.Unit" />
    <InternalsVisibleTo Include="ModularOutbox.PostgreSQL.Tests.Integration" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Scripts\**\*.sql" />
  </ItemGroup>
</Project>
