-- ==============================================================================
-- SCHEMA & UTILITIES
-- ==============================================================================
CREATE SCHEMA IF NOT EXISTS "$schema$";

-- ==============================================================================
-- TABLES
-- ==============================================================================
-- Stores integration events generated by application transactions prior to publication.
CREATE TABLE IF NOT EXISTS "$schema$".outbox_messages (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  message_id uuid NOT NULL,
  message_type varchar(500) NOT NULL,
  payload jsonb NOT NULL,
  created_at_utc timestamptz NOT NULL DEFAULT NOW(),
  processed_at_utc timestamptz,
  locked_until_utc timestamptz, -- Prevents concurrent workers from processing the same row
  retry_count int NOT NULL DEFAULT 0,
  last_error text
);

-- Tracks processed events per consumer to enforce idempotency in at-least-once delivery.
CREATE TABLE IF NOT EXISTS "$schema$".inbox_messages (
  message_id uuid NOT NULL,
  consumer_name varchar(255) NOT NULL,
  processed_at_utc timestamptz NOT NULL,
  CONSTRAINT pk_inbox_messages PRIMARY KEY (message_id, consumer_name)
);

-- ==============================================================================
-- INDEXES: OUTBOX MESSAGES
-- ==============================================================================
-- ------------------------------------------------------------------------------
-- Index: idx_outbox_unprocessed
-- Target Query: SELECT * FROM outbox_messages WHERE processed_at_utc IS NULL ORDER BY id ASC LIMIT :batchSize
--
--   1. PARTIAL INDEX: Only indexes rows where processed_at_utc IS NULL. As messages are processed,
--      they are automatically omitted from this index, keeping its size tiny and cached in RAM.
--   2. FIFO ORDERING: The (id ASC) ordering allows the OutboxDeliveryService worker to instantly
--      fetch the oldest unprocessed batch using an Index Scan without expensive in-memory sorts.
-- ------------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_outbox_unprocessed ON "$schema$".outbox_messages (id ASC)
WHERE
  processed_at_utc IS NULL;

-- ------------------------------------------------------------------------------
-- Index: idx_outbox_message_id
-- Target Query: SELECT * FROM outbox_messages WHERE message_id = :messageId
--
--   1. UNICITY ENFORCEMENT: Enforces strict uniqueness for outbox event UUIDs at the database level.
--   2. O(1) LOOKUPS: Provides instant B-Tree point lookups when checking or troubleshooting
--      specific event IDs by system administrators or diagnostic tools.
-- ------------------------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS idx_outbox_message_id ON "$schema$".outbox_messages (message_id);

-- ------------------------------------------------------------------------------
-- Index: idx_outbox_cleanup
-- Target Query: DELETE FROM outbox_messages WHERE processed_at_utc < :cleanupThreshold
--
--   1. PARTIAL INDEX: Excludes active/unprocessed messages (WHERE processed_at_utc IS NOT NULL).
--   2. EFFICIENT PRUNING: Allows the OutboxCleanupService background worker to locate expired
--      processed events via range scan without performing a costly Full Table Scan on active events.
-- ------------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_outbox_cleanup ON "$schema$".outbox_messages (processed_at_utc)
WHERE
  processed_at_utc IS NOT NULL;

-- ==============================================================================
-- INDEXES: INBOX MESSAGES
-- ==============================================================================
-- ------------------------------------------------------------------------------
-- Index: idx_inbox_cleanup
-- Target Query: DELETE FROM inbox_messages WHERE processed_at_utc < :cleanupThreshold
--
--   1. RETENTION PRUNING: Enables fast range deletion of aged inbox idempotency records
--      past their configured retention window (CleanupAfter).
--   2. PREVENTS BLOAT: Prevents the inbox tracking table from growing indefinitely in high-throughput systems.
-- ------------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_inbox_cleanup ON "$schema$".inbox_messages (processed_at_utc);

-- ------------------------------------------------------------------------------
-- Index: idx_inbox_consumer_status
-- Target Query: SELECT * FROM inbox_messages WHERE consumer_name = :consumerName AND processed_at_utc > :since
--
--   1. COMPOSITE LOOKUP: Combines consumer context and time range for targeted filtering.
--   2. METRICS & AUDITING: Optimizes consumer-specific queries, metrics dashboards,
--      and diagnostic checks without scanning records belonging to other services/modules.
-- ------------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_inbox_consumer_status ON "$schema$".inbox_messages (consumer_name, processed_at_utc);
