<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Resilience" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModularOutbox.Abstractions\ModularOutbox.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ModularOutbox.EntityFrameworkCore" />
    <InternalsVisibleTo Include="ModularOutbox.PostgreSQL" />
    <InternalsVisibleTo Include="ModularOutbox.Core.Tests" />
  </ItemGroup>
</Project>
